name: SonarCloud

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        working-directory: ./Backend
        run: dotnet restore WSBInvestmentPredictor.Backend.sln

      - name: Build
        working-directory: ./Backend
        run: dotnet build WSBInvestmentPredictor.Backend.sln --no-restore

      - name: Run tests
        working-directory: ./Backend
        run: dotnet test ./tests/Prediction/WSBInvestmentPredictor.Prediction.Tests/WSBInvestmentPredictor.Prediction.UnitTests.csproj --no-build --verbosity normal

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./Backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Bodzioss_WSBInvestmentPredictor
          SONAR_ORGANIZATION: bodzioss
