name: SonarCloud

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dotnet-sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Add tool path to environment
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        working-directory: ./Backend
        run: dotnet restore

      - name: Begin SonarCloud analysis
        working-directory: ./Backend
        run: |
          dotnet sonarscanner begin /k:"Bodzioss_WSBInvestmentPredictor" \
            /o:"bodzioss" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

      - name: Build solution
        working-directory: ./Backend
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with dotnet-coverage
        working-directory: ./Backend
        run: dotnet-coverage collect "dotnet test --no-build --configuration Release" -f xml -o "coverage.xml"

      - name: End SonarCloud analysis
        working-directory: ./Backend
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
